version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - migrations
    networks:
      - sanic-network

  db:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sanic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sanic-network

volumes:
  postgres_data:

networks:
  sanic-network: