"""Изменил тип поля id

Revision ID: 6d391f5b08d0
Revises: b54e9f697fe2
Create Date: 2025-03-09 12:19:51.978443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d391f5b08d0'
down_revision: Union[str, None] = 'b54e9f697fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # Для безопасного изменения первичного ключа в PostgreSQL
    op.execute('ALTER TABLE "user" DROP CONSTRAINT user_pkey CASCADE')
    
    # Добавляем временную колонку с UUID
    op.add_column('user', 
        sa.Column('uuid', 
            postgresql.UUID(as_uuid=True),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False
        )
    )
    
    # Создаем новый первичный ключ
    op.create_primary_key('user_pkey', 'user', ['uuid'])
    
    # Удаляем старую колонку id
    op.drop_column('user', 'id')
    
    # Переименовываем uuid -> id
    op.alter_column('user', 'uuid', new_column_name='id')

def downgrade():
    # Аналогичная логика для отката
    op.execute('ALTER TABLE "user" DROP CONSTRAINT user_pkey CASCADE')
    
    op.add_column('user',
        sa.Column('old_id', sa.Integer, autoincrement=True, nullable=False)
    )
    
    op.create_primary_key('user_pkey', 'user', ['old_id'])
    
    op.drop_column('user', 'id')
    
    op.alter_column('user', 'old_id', new_column_name='id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
